name: Build Powerpay-Kernel
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - qa
          - stage
          - prod
      oci_bucket:
        description: 'OCI Object Storage Bucket'
        required: true
        default: 'ppv2-1-dev-m2repo'
        type: choice
        options:
          - ppv2-1-dev-m2repo
          - ppv2-1-prod-m2repo
      skipTests:
        description: 'Skip tests during build'
        required: true
        default: 'false'
        type: boolean          
env:
  OCI_BUCKET_NAME: ${{ github.event.inputs.oci_bucket }}
  SKIP_TESTS: ${{ github.event.inputs.skipTests }}
  OCI_REGION: ap-singapore-1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Set up Maven 3.2.5
        run: |
          wget https://archive.apache.org/dist/maven/maven-3/3.2.5/binaries/apache-maven-3.2.5-bin.tar.gz
          tar -xzf apache-maven-3.2.5-bin.tar.gz
          sudo mv apache-maven-3.2.5 /opt/
          echo 'export M2_HOME=/opt/apache-maven-3.2.5' >> $GITHUB_ENV
          echo 'export PATH=$M2_HOME/bin:$PATH' >> $GITHUB_ENV

      - name: Install OCI CLI prerequisites
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip python3-venv

      - name: Install OCI CLI
        run: |
          python3 -m venv ~/oci-cli-venv
          source ~/oci-cli-venv/bin/activate
          pip install oci-cli

      - name: Verify OCI CLI installation
        run: |
          source ~/oci-cli-venv/bin/activate
          oci --version

      - name: Configure OCI CLI
        run: |
          mkdir -p ~/.oci
          echo [DEFAULT] >> ~/.oci/config
          echo user="${{ secrets.OCI_DEV_USER_OCID }}" >> ~/.oci/config
          echo fingerprint="${{ secrets.OCI_DEV_KEY_FINGERPRINT }}" >> ~/.oci/config
          echo key_file=~/.oci/oci_api_key.pem >> ~/.oci/config
          echo tenancy="${{ secrets.OCI_DEV_TENANCY_OCID }}" >> ~/.oci/config
          echo region="${{ secrets.OCI_REGION }}" >> ~/.oci/config
          echo "${{ secrets.OCI_DEV_PRIVATE_KEY }}" >> ~/.oci/oci_api_key.pem
          chmod 600 ~/.oci/config ~/.oci/oci_api_key.pem

      - name: Download dependencies from OCI
        run: |
          source ~/oci-cli-venv/bin/activate
          mkdir -p ~/.m2/repository
          oci os object bulk-download \
            --bucket-name ${{ env.OCI_BUCKET_NAME }} \
            --dest-dir ~/.m2/repository

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: |
          if [ "${{ env.SKIP_TESTS }}" = "true" ]; then
            MAVEN_ARGS="-DskipTests"
          else
            MAVEN_ARGS=""
          fi  
          mvn clean install ${MAVEN_ARGS}
          echo "mvn clean install ${MAVEN_ARGS}"

      - name: Upload artifacts and dependencies to OCI
        run: |
          source ~/oci-cli-venv/bin/activate
          oci os object bulk-upload \
            --bucket-name ${{ env.OCI_BUCKET_NAME }} \
            --src-dir ~/.m2/repository
