name: Build Powerpay-Kernel

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - qa
          - stage
          - prod
      oci_bucket:
        description: 'OCI Object Storage Bucket'
        required: true
        default: 'ppv2-1-dev-m2repo'
        type: choice
        options:
          - ppv2-1-dev-m2repo
          - ppv2-1-prod-m2repo
      skipTests:
        description: 'Skip tests during build'
        required: true
        default: 'false'
        type: boolean          

env:
  OCI_BUCKET_NAME: ${{ github.event.inputs.oci_bucket }}
  SKIP_TESTS: ${{ github.event.inputs.skipTests }}
  OCI_REGION: ap-singapore-1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: '17'

    - name: Set up Maven 3.2.5
      run: |
        wget https://archive.apache.org/dist/maven/maven-3/3.2.5/binaries/apache-maven-3.2.5-bin.tar.gz
        tar -xzf apache-maven-3.2.5-bin.tar.gz
        sudo mv apache-maven-3.2.5 /opt/
        echo 'export M2_HOME=/opt/apache-maven-3.2.5' >> $GITHUB_ENV
        echo 'export PATH=$M2_HOME/bin:$PATH' >> $GITHUB_ENV

    - name: Install OCI CLI
      run: |
        sudo apt update
        curl -L https://raw.githubusercontent.com/oracle/oci-cli/master/scripts/install/install.sh | bash -s -- --accept-all-defaults
        echo 'export PATH=$HOME/.oci-cli/bin:$PATH' >> $GITHUB_ENV
        echo 'PATH updated for OCI CLI'

    - name: Verify OCI CLI Installation
      run: |
        export PATH=$HOME/.oci-cli/bin:$PATH
        oci --version
        echo "OCI CLI installation verified successfully"

    - name: Configure OCI credentials
      run: |
        mkdir -p ~/.oci
        echo -e "${{ secrets.OCI_DEV_PRIVATE_KEY }}" > ~/.oci/oci_api_key.pem
        cat <<EOT > ~/.oci/config
        [DEFAULT]
        user=${{ secrets.OCI_DEV_USER_OCID }}
        fingerprint=${{ secrets.OCI_DEV_KEY_FINGERPRINT }}
        key_file=~/.oci/oci_api_key.pem
        tenancy=${{ secrets.OCI_DEV_TENANCY_OCID }}
        region=${{ env.OCI_REGION }}
        EOT
        chmod 600 ~/.oci/oci_api_key.pem

    - name: Download dependencies from OCI
      run: |
        export PATH=$HOME/.oci-cli/bin:$PATH
        mkdir -p ~/.m2/repository
        oci os object bulk-download \
          --bucket-name ${{ env.OCI_BUCKET_NAME }} \
          --destination ~/.m2/repository

    - name: Cache Maven packages
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Build with Maven
      run: |
        if [ "${{ env.SKIP_TESTS }}" = "true" ]; then
          MAVEN_ARGS="-DskipTests"
        else
          MAVEN_ARGS=""
        fi  
        mvn clean install ${MAVEN_ARGS}
        echo "mvn clean install ${MAVEN_ARGS}"

    - name: Upload artifacts and dependencies to OCI
      run: |
        export PATH=$HOME/.oci-cli/bin:$PATH
        oci os object bulk-upload \
          --bucket-name ${{ env.OCI_BUCKET_NAME }} \
          --src-dir ~/.m2/repository
